---

- name: dnsmasq | Install packages
  become: true
  notify:
    - reload_daemon
  package:
    name: "{{ item }}"
    state: present
  loop:
    - dnsmasq
    - resolvconf

- name: dnsmasq | Check if folder exist
  stat:
    path: "{{ item }}"
  register: folder_status_dnsmasq
  loop:
    - "{{ path.settings_dnsmasq }}"

- name: dnsmasq | Create folders
  become: true
  file:
    dest: "{{ item.item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: not item.stat.exists | bool
  loop: "{{ folder_status_dnsmasq.results }}"

- name: dnsmasq | Manage configuration
  become: true
  notify:
    - reload_daemon
    - restart_dnsmasq
    - restart_resolved
  template:
    dest: "{{ path.settings_dnsmasq }}/{{ item }}"
    src: "{{ item }}.j2"
    owner: "root"
    group: "root"
    mode: 0644
  loop:
    - dnsmasq

- name: dnsmasq | Start and enable unit
  become: true
  notify:
    - restart_dnsmasq
    - restart_resolved
  systemd:
    name: "dnsmasq"
    masked: no
    enabled: yes
    state: started
