---

- name: dnsmasq | Install packages
  become: true
  notify:
    - reload_daemon
    - restart_dnsmasq
  package:
    name: dnsmasq
    state: present

- name: dnsmasq | Install resolvconf (Debian)
  become: true
  notify:
    - reload_daemon
    - restart_resolved
  package:
    name: resolvconf
    state: present
  when: ansible_os_family == 'Debian'

- name: dnsmasq | Install openresolv (RedHat)
  block:

    - name: openresolv | add repo
      become: true
      yum_repository:
        name: macieks-openresolv-epel-7
        description: "Openresolv"
        baseurl: "https://copr.fedorainfracloud.org/coprs/macieks/openresolv/repo/epel-7/macieks-openresolv-epel-7.repo"
        gpgcheck: false
        enabled: true

    - name: openresolv | install
      become: true
      notify:
        - reload_daemon
      package:
        name: openresolv
        state: present

  # TODO: Disabled; not finished
  when: ansible_os_family == 'RedHat' and dnsmasq.yum.openresolv and false

- name: dnsmasq | Check if folder exist
  stat:
    path: "{{ item }}"
  register: folder_status_dnsmasq
  loop:
    - "{{ path.settings_dnsmasq }}"

- name: dnsmasq | Create folders
  become: true
  file:
    dest: "{{ item.item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: not item.stat.exists | bool
  loop: "{{ folder_status_dnsmasq.results }}"

- name: dnsmasq | Manage configuration
  become: true
  notify:
    - reload_daemon
    - restart_dnsmasq
  template:
    dest: "{{ path.settings_dnsmasq }}/{{ item }}"
    src: "{{ item }}.j2"
    owner: "root"
    group: "root"
    mode: 0644
  loop:
    - dnsmasq

- name: dnsmasq | Start and enable unit
  become: true
  notify:
    - restart_dnsmasq
  systemd:
    name: "dnsmasq"
    masked: no
    enabled: yes
    state: started
