---

# NOTE: Only default ports for now!
- name: Firewalld | Manage settings
  become: true
  notify:
    - reload_daemon
    - restart_firewalld
  firewalld:
    permanent: yes
    state: enabled
    port: "{{ item }}"
  loop:
    - 8300/tcp
    - 8301/tcp
    - 8302/tcp
    - 8500/tcp
    - 8501/tcp
    - 8502/tcp
    - 21000-21255/tcp
    - 8600/tcp
    - 8301/udp
    - 8302/udp
    - 8600/udp
    - 21000-21255/udp
