---

- name: consul | enable encryption
  become: true
  notify:
  - reload_systemd_daemon
  - restart_unit_consul
  template:
    dest: "{{ base_dir['configs'] }}/{{ bin_name['consul'] }}.d/{{ item }}"
    src: "{{ bin_name['consul'] }}/{{ item }}.j2"
    owner: "{{ bin_name['consul'] }}"
    group: "{{ bin_name['consul'] }}"
    mode: 0640
  loop:
  - 50-encrypt.hcl
