---

- name: consul | create installation folders
  become: true
  file:
    path: "{{ base_dir['packages'] }}/{{ bin_name['consul'] }}/{{ consul['version'] }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: consul | extract binary
  become: true
  unarchive:
    src: "{{ base_dir['downloads'] }}/{{ package_name_consul }}.zip"
    dest: "{{ base_dir['packages'] }}/{{ bin_name['consul'] }}/{{ consul['version'] }}"
    remote_src: yes

- name: consul | symlink binary
  become: true
  file:
    src: "{{ base_dir['packages'] }}/{{ bin_name['consul'] }}/{{ consul['version'] }}/{{ bin_name['consul'] }}"
    path: "{{ base_dir['binaries'] }}/{{ bin_name['consul'] }}"
    state: link
