---

- name: consul | check if file is downloaded
  become: false
  stat:
    path: "{{ os_dir_temp }}/{{ package_name_consul }}.zip"
  register: package_status_consul

- block:

  - name: consul | download package
    become: false
    get_url:
      url: "{{ package_url_consul }}"
      dest: "{{ os_dir_temp }}"
      checksum: "sha256:{{ checksum_url_consul }}"
      validate_certs: false
    register: download_status_consul

  when: not package_status_consul['stat']['exists']
