---

- name: consul | extract binary
  become: true
  unarchive:
    src: "{{ os_dir_temp }}/{{ package_name_consul }}.zip"
    dest: "{{ os_dir_packages }}/consul/{{ consul_version }}"
    owner: consul
    group: consul
    remote_src: yes

- name: consul | symlink binary
  become: true
  notify:
  - restart_unit_consul
  file:
    src: "{{ os_dir_packages }}/consul/{{ consul_version }}/consul"
    dest: "{{ os_dir_binaries }}/consul"
    owner: consul
    group: consul
    state: link
