---

# ==============================================================================
#  Check if os is supported by role
# ==============================================================================

- include: assert_os.yml

# ==============================================================================
#  Include variables based on operating system
# ==============================================================================

- name: include variables based on operating system
  include_vars: "{{ lookup('first_found',possible_files) }}"
  vars:
    possible_files:
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - "coreos.yaml"

# ==============================================================================
#  Install only if requested version doesn't already exist
# ==============================================================================

#- include: assert_version_installed.yml

- name: Consul | check if version already installed
  stat:
    path: "{{ os_dir_packages }}/consul/{{ consul_version }}"
  register: version_exists

- block:
  - include: download.yml
  - include: user.yml
  - include: folders.yml
  - include: install.yml
  when: not version_exists['stat']['exists']

# ==============================================================================
#  Configure service
# ==============================================================================

- include: configure.yml
- include: initialize.yml
