---
# handlers file for consul

- name: reload_daemon
  become: true
  systemd:
    daemon_reload: yes

- name: restart_unit
  become: true
  systemd:
    name: "{{ application }}"
    state: restarted

# Optional settings handlers

- name: restart_dnsmasq
  become: true
  systemd:
    name: dnsmasq
    state: restarted

- name: restart_resolved
  become: true
  systemd:
    name: systemd-resolved
    state: restarted

- name: restart_firewalld
  become: true
  systemd:
    name: firewalld
    state: restarted
